#!/usr/bin/env bash

set -euo pipefail

### Global settings ###
domain=""
output_dir=""




### Configuration ###
pd_tools=("subfinder" "shuffledns" "alterx" "dnsx" "naabu" "httpx" "katana" "urlfinder" "nuclei")




### Functions ###

# Check if script tools are isntalled.
check_script_tools() {
echo -e "\n[INF] Checking if required tools are installed...\n"

for tool in "${pd_tools[@]}"; do
    if command -v "$tool" &> /dev/null; then
        echo -e "[INF] $tool is already installed."
        continue
    else
        echo -e "[WRN] $tool is not installed."
    fi
done
}

# Install script tools
install_script_tools() {
    echo -e "[INF] Installing required tools...\n"

    (IFS=,
    pdtm -i "${pd_tools[*]}" -igp)
    
    if [[ $? -eq 0 ]]; then
        echo "[INF] All required tools were installed."
    else
        echo "[ERR] Failed to install required tools."
        return 1
    fi
}
#install_script_tools
#exit 0
# Function to define domain and output directory if unspecified.
define_variables() {

    while [[ -z "$domain" ]]; do
        read -e -r -p "Please specify a domain: " domain
        [[ -z  "$domain" ]] && echo "[ERR] $domain cannot be empty."
    done

    local strip_protocol="${domain#*://}"
    local strip_name="${strip_protocol#www.}"
    local clean_name="${strip_name%%/*}"

    if [[ -n "$output_dir" && -d "$output_dir" ]]; then
       echo "[INF] Using existing directory: $output_dir"
       return 0
    fi

    if [[ -z "$output_dir" ]]; then
        output_dir="$clean_name"
    fi

    if [[ ! -d "$output_dir" ]]; then
        mkdir -p "./$output_dir"
        echo "[INF] Output will be stored in: $output_dir"
    else
        echo "[INF] Output will be stored in: $output_dir"
    fi
}

# Confirm actions
#confirm_action() {}

# Configure Subfinder
#set_subfinder() {}

# Run Subfinder
run_subfinder() {
    local output_file=""
    echo -e "[INF] Starting subfinder.\n"
    #subfinder -d <domain> -all -o domains.txt
    subfinder -d "$domain" -all -o "$output_file"
}

# Configure ShuffleDNS
#set_shuffledns() {}

# Run ShuffleDNS
#run_shuffledns(){}

# Configure AlterX
#set_alterx() {}

# Run AlterX
#run_alterx() {}

# Configure DNSX
#set_dnsx() {}

# Run DNSX
#run_dnsx() {}

# Configure Naabu
#set_naabu() {}

# Run Naabu
#run_naabu() {}

# Configure HTTPX
#set_httpx() {}

# Run HTTPX
#run_httpx() { }
# Configure Katana

#set_katana() {}

# Run Katana
#run_katana() {}

# Generate report
#generate_report() {}

##################
### Main Logic ###
##################

# Flags options
install_tools=()
verbose=false

while getopts ":i:vh" opt; do
    case $opt in
        i)
            if [[ "$OPTARG" == "tools" ]]; then
                install_tools+=("$OPTARG")
            else
                echo "Error: Invalid argument for -i. Use 'tools'." >&2
            fi
            ;;
        v) verbose=true ;;
        h)
            echo "Usage: $0 [-i pdmt] [-i tools] [-v verbose] [-h help]"
            exit 0
            ;;
        *) 
            echo "Usage: $0 [-i pdmt] [-i tools] [-v verbose] [-h help]"
            exit 0
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
    esac
done
shift $((OPTIND-1))

for task in "${install_tools[@]}"; do
    case "$task" in
        "tools")
            #echo -e "\n[INF] Starting tools installation..."
            check_script_tools
            install_script_tools
            ;;
    esac
done

[[ $verbose == true ]] && set -x

#### ------ Phase 1: Asset Discovery ------ ####

## Logo here
## Legal disclaimer here
## Initial instructions here

# Define domain and output directory

# Configure and run Subfinder

# Configure and run ShuffleDNS

# Configure and run AlterX

# Configure and run DNSX

# Configure and run Naabu
#echo "[WRN] This scan is active / Noisy"

#### ------ Phase 2: Content Discovery ---- ####

# Configure and run HTTPX

# Configure and run Katana
#echo "[WRN] This scan is active / Noisy"

# Consider run URLFinder with Katana to gather URLs from external sources

#### ------ Phase 3: Report Generation ------ ####

# Generate report

